### ISSUE TITLE
task mutates string given as task_name

### ISSUE THREAD

**Issue by petewest** [chef-cookbooks/windows#289] opened 2015-10-20 15:19 UTC
When using windows_task LWRP it mutates the string given as `task_name`

```ruby
task_name = 'task_name_to_modify'
old_task_name = task_name.dup

windows_task task_name do
  action :disable
end

old_task_name == task_name # false
task_name # '\task_name_to_modify'
```

The offending line is https://github.com/chef-cookbooks/windows/blob/master/providers/task.rb#L149 : `pathed_task_name = @new_resource.task_name[0, 1] == '\\' ? @new_resource.task_name : @new_resource.task_name.prepend('\\')`

**Comment by chrisgit** [comment] 2016-05-11 09:02
Code has been changed to

````
pathed_task_name = @new_resource.task_name.start_with?('\\') ? @new_resource.task_name : "\\#{@new_resource.task_name}"
````

So I think this can be closed, it was also the cause of these issues 

https://github.com/chef-cookbooks/windows/issues/342
https://github.com/chef-cookbooks/windows/issues/271

@petewest Can you confirm?

Thanks

**Comment by petewest** [comment] 2016-05-11 10:37
That's great, thanks!

**Comment by mwrock** [comment] 2016-05-11 22:35
thanks for following up on this @chrisgit . I'm closing.

**Closed by mwrock** 2016-05-11 22:35 UTC
