### ISSUE TITLE
windows_feature powershell install on Windows 2008R2 not installing Feature

### ISSUE THREAD

**Issue by MikeLingenfelter** [chef-cookbooks/windows#549] opened 2018-04-11 18:35 UTC
### Cookbook version
4.1.4

### Chef-client version
14.0.190

### Platform Details
Windows 2008 R2 SP1

### Scenario:
When using windows_feature and install_method :windows_feature_powershell, it returns a message "The Windows feature <fearture name> is not available on this version of Windows."  This was tested for severval Features avalible on the server.  If you use install_method :windows_feature_dism, features can be installed.

Powershell 5.1 is installed on the server.

### Steps to Reproduce:
Tested widows_feature install on Windows 2008R2, 2012R2 and 2016.  Only Windows 2008R2 is having the problem.

### Expected Result:
Windows Feature is installed.

### Actual Result:
Error on Windows 2008R2 systems.

Recipe: test::default
   * windows_feature[SNMP-WMI-Provider] action install
     * windows_feature_powershell[SNMP-WMI-Provider] action install

       ================================================================================
       Error executing action `install` on resource 'windows_feature_powershell[SNMP-WMI-Provider]'
       ================================================================================

       RuntimeError
       ------------
       The Windows feature snmp-wmi-provider is not available on this version of Windows. Run 'Get-WindowsFeature' to see the list of available feature names.

       Resource Declaration:
       ---------------------
       # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb

 47:     declare_resource(subresource, new_resource.name) do
 48:       action desired_action
 49:       feature_name new_resource.feature_name
 50:       source new_resource.source if new_resource.source
 51:       all new_resource.all
 52:       timeout new_resource.timeout
 53:       management_tools new_resource.management_tools if subresource == :windows_feature_powershell
 54:     end
 55:   end

       Compiled Resource:
       ------------------
       # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb:47:in `run_default_subresource'

       windows_feature_powershell("SNMP-WMI-Provider") do
  action [:install]
  default_guard_interpreter :default
  declared_type :windows_feature_powershell
  cookbook_name "test"
  feature_name ["snmp-wmi-provider"]
  all false
  timeout 600
  management_tools false
       end

       System Info:
       ------------
       chef_version=14.0.190
       platform=windows
       platform_version=6.1.7601
       ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
       program_name=C:/opscode/chef/bin/chef-client
       executable=C:/opscode/chef/bin/chef-client

**Comment by s1mark** [comment] 2018-04-16 13:30
I also ran into this issue. The problem is that the https://github.com/chef-cookbooks/windows/blob/c0355531e13fd0758281f3a81198e108ded960d7/resources/feature_powershell.rb#L196
does not populate properly the `raw_list_of_features` object because there is no `InstallState` property in the `Get-WindowsFeature` objects
thus the json object results is:
```json
[
  {"Name":"AD-Certificate","InstallState":null},
  {"Name":"ADCS-Cert-Authority","InstallState":null},
  {"Name":"ADCS-Web-Enrollment","InstallState":null},
  {"Name":"ADCS-Online-Cert","InstallState":null},
  ...
]
```
Because of the `"InstallState":null` result, the 
https://github.com/chef-cookbooks/windows/blob/master/resources/feature_powershell.rb#L179-L188
case will return an empty `node['powershell_features_cache']` mash and cause error raise

* OS version 2008R2
* PS version 4.0
* .Net 4.5

Proposed solution:
`Get-WindowsFeature | Select-Object -Property Name,Installed | ConvertTo-Json -Compress`
which will return the following json
```json
[
  {"Name":"AD-Certificate","Installed":false},
  {"Name":"ADCS-Cert-Authority","Installed":false},
  {"Name":"ADCS-Web-Enrollment","Installed":false},
  {"Name":"ADCS-Online-Cert","Installed":false},
  ...
```

So it seems that Windows Server 2008R2 only determines a boolean for the install state whereas from Windows Server 2012 there are 3 states (Removed, Installed, Available)

**Comment by tas50** [comment] 2018-05-31 19:13
We can't switch to a installed or not value because that fundamentally breaks functionality on later Windows editions, but I'll see what sort of error handling we could introduce for Windows 2008 R2. It's tough because 2k8r2 is so ridiculously dated at this point even if you install modern .NET / PowerShell.

**Comment by MikeLingenfelter** [comment] 2018-06-01 14:56
Thanks for the update.  I get it, we are trying to get off of 2008 as soon as possible.

**Comment by tas50** [comment] 2018-06-11 16:00
This is fixed on master and I'll see if I can get a release out today. The same functionality will also ship in Chef 14.3

**Closed by tas50** 2018-06-11 16:00 UTC

**Comment by s1mark** [comment] 2018-06-12 05:49
@tas50 sounds and looks great! Thank you for this fix!
