### ISSUE TITLE
windows_task user wrong when :user not specified and command line options present

### ISSUE THREAD

**Issue by zdenko-s** [chef-cookbooks/windows#308] opened 2015-11-25 08:22 UTC
Create task from documentation and remove user part
windows_task 'chef-client' do
  cwd 'C:\chef\bin'
  command 'chef-client -L C:\chef\logs\'
  action :change
end
Run recipe in zero mode (-z). Check Windows Task Scheduler. New task will be created and user identity is not 'SYSTEM' but 'computer_name\ADMINISTRATOR'
Delete task and remove command line arguments from command. When running recipe, correct 'SYSTEM' account is used.

**Comment by mwrock** [comment] 2015-11-27 17:25
Hmm. I'm unable to reproduce:
started with:
```windows_task 'task_for_system' do
  command  'chef-client -L C:\chef\logs'
  user 'vagrant'
  password 'vagrant'
  cwd ENV['TEMP']
end
```
then:
```
windows_task 'task_for_system' do
  command  'chef-client -L C:\chef\logs'
  cwd ENV['TEMP']
  action :change
end
```

**Comment by tas50** [comment] 2017-01-03 22:01
Closing as not reproducible unless we get additional information

**Closed** 2017-01-03 22:01 UTC
