### ISSUE TITLE
windows_feature_powershell will not install Windows Features with sources

### ISSUE THREAD

**Issue by Y29nVCt** [chef-cookbooks/windows#517] opened 2017-12-21 21:02 UTC
### Cookbook version
3.41

### Chef-client version
13.6.4

### Platform Details
Windows Server 2012 R2 using packer template at https://github.com/mwrock/packer-templates

### Scenario:
Install Windows Features using `install_method :windows_feature_powershell`

### Steps to Reproduce:
Converge using this recipe
````
windows_feature 'MSMQ-Server' do
  source 'c:\sources'
  install_method :windows_feature_powershell
  action :install
end
````

### Expected Result:
MSMQ-Server Windows Feature is installed

### Actual Result:
Windows Feature is not installed. There is a warning message...
>WARN: Requested feature MSMQ-Server is not available on this system.

**Comment by dpbustos** [comment] 2018-02-20 04:01
I've reproduced this issue too. It's an issue for features with the source files not available in the OS, these are marked as 'Removed' in the Install State property when you run Get-WindowsFeature.

Simplest fix would be to remove the filtering out of 'Removed' features, in Line 58 of **feature_powershell.rb**.

**Current Code:**
powershell_out("@(Get-WindowsFeature #{to_array(new_resource.feature_name).join(',')} | ?{$_.InstallState -ne \'Removed\'}).count", timeout: new_resource.timeout)

**Suggested Fix:**
powershell_out("@(Get-WindowsFeature #{to_array(new_resource.feature_name).join(',')}).count", timeout: new_resource.timeout)

Anyone have any thoughts or suggestions to above?

Thanks,


David

**Comment by tas50** [comment] 2018-04-12 21:38
@Y29nVCt @dpbustos Can you try this with the very latest cookbook. The windows_feature resources have been entirely rewritten which worked out a bunch of edge cases like this.

**Comment by tas50** [comment] 2018-07-05 18:17
Closing this out since we haven't heard back

**Closed** 2018-07-05 18:17 UTC
Labels: Status: Pending Contributor Response
