### ISSUE TITLE
Error Encoding conversion with chef_gem on fr-FR windows using chef 12.10

### ISSUE THREAD

**Issue by lbn-chef-team** [chef-cookbooks/windows#368] opened 2016-06-03 13:03 UTC
### Cookbook version

windows 1.42.0
### Chef-client version

chef-client 12.10.24 x64 (ruby 2.1.0)
### Platform Details

Windows 2012 R2 (french) running on Hyper-V Standard 
notice: The problem occurs only on FRENCH server (fr-FR)
### Scenario:

Running windows::default cookbook and I got always this error:
FATAL: Encoding::UndefinedConversionError: chef_gem[win32-api](windows::default line 23)
had an error: Encoding::UndefinedConversionError: 
U+2019 to CP850 in conversion from UTF-16LE to UTF-8 to CP850
### Steps to Reproduce:

Install chef-client 12.10.24 (x64) on a windows 2012r2 server in french (fr-FR)
setting the windows cookbook in C:\Chef\cookbooks
running CMD and prompt to C:\chef
Running then command: chef-client -z -o recipe['windows::default']

I have'nt this problem on this server when running on chef 12.8.1 (ruby 2.0.0)
Maybe windows cookbook is not compatible with ruby 2.1.0 (on non-english server)?

Thanks for your help :)

Regards,

**Comment by mwrock** [comment] 2016-06-03 21:00
Its hard to say what the root is. I'd tend to doubt its the ruby version since it seems the higher versions tend to fix encoding errors rather than create them. It may be the version of the win32-api gem. One thing that would be helpful is to get a stack trace of the error. You can get that with debug logging. `-l debug`

There can certainly be issues with some codepages having incompatibilities with certain UTF-8 encoded characters. One way to possibly work around the issue can be to run `chcp 65001` in your `cmd` window prior to the chef run to force the session to use the UTF-8 codepage.

**Comment by lbn-aaio-team** [comment] 2016-06-06 08:33
Hello Matt,

Thanks for your reply.

I found the following workaround by changing the line 70 in:
..\opscode\chef\embedded\lib\ruby\2.1.0\win32\registry.rb

  #LOCALE = Encoding.find(Encoding.locale_charmap)
  LOCALE = Encoding::UTF_8

After this change, when running chef-client, the command terminate successfully.
May the problem is related to https://github.com/chef/chef/issues/4897?

Here the debug trace:

2016-06-06T10:28:26+02:00] INFO: Processing chef_gem[win32-api] action install (windows::default line 23)
[2016-06-06T10:28:26+02:00] DEBUG: Providers for generic chef_gem resource enabled on node include: [Chef::Provider::Package::Rubygems]
[2016-06-06T10:28:26+02:00] DEBUG: Provider for action install on resource chef_gem[win32-api] is Chef::Provider::Package::Rubygems
[2016-06-06T10:28:26+02:00] DEBUG: chef_gem[win32-api] using gem 'C:/LinkByNet/Programs/opscode/chef/embedded/bin/gem'
[2016-06-06T10:28:26+02:00] DEBUG: chef_gem[win32-api] found installed gem win32-api version 1.5.3 matching win32-api (>= 0)
[0m
================================================================================[0m
[31mError executing action `install` on resource 'chef_gem[win32-api]'[0m
================================================================================[0m

[0mEncoding::UndefinedConversionError[0m
----------------------------------[0m
U+2019 to CP850 in conversion from UTF-16LE to UTF-8 to CP850[0m

[0mResource Declaration:[0m
---------------------[0m
# In C:/Users/LBN_p.deprey/.chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb
[0m
[0m 23:   chef_gem win_gem do
[0m 24:     options '--platform=mswin32'
[0m 25:     action :install
[0m 26:     compile_time false if respond_to?(:compile_time)
[0m 27: 	source "http://repository.lbn.fr/win/Softs/chef/gems/"
[0m 28:   end
[0m 29: end
[0m
[0mCompiled Resource:[0m
------------------[0m
# Declared in C:/Users/LBN_p.deprey/.chef/local-mode-cache/cache/cookbooks/windows/recipes/default.rb:23:in `block in from_file'
[0m
[0mchef_gem("win32-api") do
[0m  package_name "win32-api"
[0m  action [:install]
[0m  retries 0
[0m  retry_delay 2
[0m  default_guard_interpreter :default
[0m  declared_type :chef_gem
[0m  cookbook_name "windows"
[0m  recipe_name "default"
[0m  options "--platform=mswin32"
[0m  source "http://repository.lbn.fr/win/Softs/chef/gems/"
[0m  gem_binary "C:/LinkByNet/Programs/opscode/chef/embedded/bin/gem"
[0mend
[0m
[0mPlatform:[0m
---------[0m
x64-mingw32[0m

[0m[2016-06-06T10:28:26+02:00] INFO: Running queued delayed notifications before re-raising exception
[2016-06-06T10:28:26+02:00] DEBUG: Re-raising exception: Encoding::UndefinedConversionError - chef_gem[win32-api] (windows::default line 23) had an error: Encoding::UndefinedConversionError: U+2019 to CP850 in conversion from UTF-16LE to UTF-8 to CP850

Best Regards,

Pierre

**Comment by lbn-aaio-team** [comment] 2016-06-06 08:39
Another method to bypass this error:

In regsitry, add this key:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor]
"Autorun"="chcp 1252"

**Comment by mwrock** [comment] 2016-06-06 21:10
In the error above. It might be helpful to run chef-client with `-l debug` to get a more precise idea where the error is occuring and determine if this is something we could fix via chef without monkey patching ruby.

**Comment by lbn-aaio-team** [comment] 2016-06-07 09:01
Here the log output of running command: chef-client -z -o recipe['windows'] -l debug
This command is launch with SYSTEM account. (as we do with the service chef-client).

[chefclient.zip](https://github.com/chef-cookbooks/windows/files/302167/chefclient.zip)

Regards,

**Comment by mwrock** [comment] 2016-06-07 14:04
Thanks! Yeah looks like a monkey patch to ruby from chef core is the only way to fix this. We have done that before but I really prefer not to especially if you have a workaround. I do see that this error occurs inside of an exception initializer so I wonder once you fix the exception case if you still run into encoding issues.

**Comment by tas50** [comment] 2017-09-09 04:02
We've removed the contents of the default recipe altogether so I'm going to close this out now. The latest release shouldn't give you issues.

**Closed by tas50** 2017-09-09 04:02 UTC
Labels: Type: Bug
