### ISSUE TITLE
Feature request : - Random Delay option in windows_task resource.

### ISSUE THREAD

**Issue by sasydharan** [chef-cookbooks/windows#400] opened 2016-10-14 07:48 UTC
### Platform Details

Any Windows 
### Expected Result:

To be able to set random delay for a scheduled task

**Comment by iancward** [comment] 2016-11-17 14:44
This appears to be a duplicate of #245

**Comment by mwrock** [comment] 2016-11-17 23:00
yup. closing

**Closed by mwrock** 2016-11-17 23:00 UTC
