### ISSUE TITLE
Windows cookbook does not support two packages with the same package name

### ISSUE THREAD

**Issue by Tech356** [chef-cookbooks/windows#192] opened 2015-03-11 13:52 UTC
### Version:
Chef Client 12.1.0
Windows Cookbook 1.36.3

### Environment:
Windows 7 64-bit
Windows Cookbook 1.36.3

### Scenario:
Install two Microsoft Visual C++ 2005 Redistributable Packages
Both packages install with a package_name of "Microsoft Visual C++ 2005 Redistributable" but with different version numbers.

### Steps to Reproduce:
1) Download vcredist packages
  - version 8.0.56336 http://www.microsoft.com/en-us/download/details.aspx?id=5638
  - version 8.0.59193 http://www.microsoft.com/en-us/download/details.aspx?id=14431

2) Run the following recipe twice

    windows_package 'Microsoft Visual C++ 2005 Redistributable 8.0.56336' do
        action :install
        package_name 'Microsoft Visual C++ 2005 Redistributable'
        source <path_to_vcredist_8.0.56336>
        version '8.0.56336'
        installer_type :custom
        options '/Q'
    end

    windows_package 'Microsoft Visual C++ 2005 Redistributable 8.0.59193' do
        action :install
        package_name 'Microsoft Visual C++ 2005 Redistributable'
        source <path_to_vcredist_8.0.59193>
        version '8.0.59193'
        installer_type :custom
        options '/Q'
    end

### Expected Result:
Both packages to install and report "up to date" on subsequent runs.

### Actual Result:
Both packages install, but one package always reinstalls in subsequent runs. 

I believe this is because the [`installed_packages`](https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_helper.rb#L103-L118) function uses a hash with the `package_name` as the key. This drops one of the packages since they have the same `package_name`. The chef client the doesn't know that the package is installed and attempts to install it. 

Running `puts installed_packages` returns only one "Microsoft Visual C++ 2005 Redistributable" listed. 

    {
        ... 
        "Microsoft Visual C++ 2005 Redistributable" => {: name => "Microsoft Visual C++ 2005 Redistributable", : version => "8.0.59193", : uninstall_string => "MsiExec.exe /X{837b34e3-7c30-493c-8f6a-2b0f04e2912c}" }, 
        "Chef Client v12.1.0" => {: name => "Chef Client v12.1.0", : version => "12.1.0.1", : uninstall_string => "MsiExec.exe /I{8693C589-4430-4E92-9241-87FF9B52C8C5}" }
    }

**Comment by btm** [comment] 2015-03-11 14:00
Have you tried this using the "package" resource (which would use the windows_package provider in core Chef)?

**Comment by Tech356** [comment] 2015-03-11 16:46
My understanding is that the built in package resource only supports MSIs.

**Comment by btm** [comment] 2015-03-11 17:58
@Tech356 yeah, you're correct, I missed that. What are these? 

I think we're going to end up putting our effort into expanding the core resource rather than rewriting how the windows cookbook differentiates between installed packages (core does it in a more reliable way already too)

**Comment by Tech356** [comment] 2015-03-11 18:23
@btm I am pretty sure they are self extracting installers. They have a cab and a MSI inside. 

From my basic knowledge it seems that when using the windows cookbook it overrides the core windows_package resource. So I can either use the windows cookbook XOR the core windows_package resource. Is that correct? Is there a plan to make the core windows_package resource able to co-exist with the windows cookbook?

**Comment by btm** [comment] 2015-03-11 18:47
@Tech356 yeah, you can use the core windows package even when the windows cookbook is in the runlist by using ```package``` (this functionality was provided by https://www.chef.io/blog/2015/02/10/chef-12-provider-resolver/).

**Comment by anthony-7** [comment] 2015-03-27 00:33
We've just come across the same problem. We're installing the C Redistributable packages for 2010, 2012 & 2013. They all have the same name (vcredist_x86.exe). This seems to be the cause of the problem because the files get cached in the same directory %userprofile%\.chef\local-mode-cache\cache. Hence each version overwrites the previous one.

**Comment by mwrock** [comment] 2015-12-08 02:20
This scenario is addressed via https://github.com/chef/chef/pull/4193 however there is something to be aware of with this particular installer.

While it is certainly possible, as observed here, for two packages to have the exact same display name to be installed together, many packages may not install "side by side" but will detect other existing packages and uninstall them prior to install.

For example even after the new package resource is added released in an upcoming chef client, installing the above to installers in the order you have them will cause the following sequence of events:

1. First C++ runtime is installed
2. Second runtime will install and uninstall the first.
3. Next client run
4. First installer will install again
5. second installer will not install because it will be seen as already installed
6. all subsequent runs will not converge either resource

So things are better but you still will have one "unexpected" converged resource. You will be able to avoid that by simply flipping the order in which these resources sit in the recipe.

**Comment by tas50** [comment] 2016-09-02 23:08
We've removed the windows_package provider in this cookbook in favor of the package provider that is built into chef now. I'm going to close this issue out. If you're still seeing the problem with that modernized code please open an issue up against chef/chef.

**Closed by tas50** 2016-09-02 23:08 UTC
