### ISSUE TITLE
windows_task does not update a task after it's been changed by a newer cookbook version

### ISSUE THREAD

**Issue by csallen1204** [chef-cookbooks/windows#407] opened 2016-11-18 23:42 UTC
### Chef-client version
Chef 12.16.42

### Platform Details
Windows 2012

### Scenario:
I have a windows task that I have made updates to even though it still has the same name. When I pushed the newer cookbook, the Windows Task wasn't updated. I assume this is because it's only checking the name of the task and not it's contents?

### Steps to Reproduce:
-make a recipe with a windows_task with action: create
-apply it to a windows 2012 server
-change the task
-apply it again
-see in the logs and in Task Scheduler that nothing was changed

### Expected Result:
There should be some logic that sees if a windows_task was modified and then overwrite the task with the new instructions.

### Actual Result:
chef-win-02.devlab.ibm.com [2016-11-18T15:29:19-08:00] INFO: Processing windows_task[IEMUpdate] action create (commerce-sst::_install_windows line 30)
chef-win-02.devlab.ibm.com [2016-11-18T15:29:19-08:00] INFO: windows_task[IEMUpdate] task already exists - nothing to do

**Comment by NimishaS** [comment] 2017-03-10 07:34
@csallen1204 , I tried with the following recipes:
```
windows_task 'chef-client' do  
  cwd 'C:\\chef\\bin'
  command 'chef-client -L C:\\chef\\logs\\'
  run_level :highest
  action :change
end
```
```
windows_task 'chef-client' do
  cwd 'C:\\chef\\bin'
  run_level :highest
  command 'ls'
  action :change
end
```

Here the command has been modified in the second recipe. I checked using `schtasks /query /tn "chef-client" /fo list /v` and the task is being modified successfully.

Please share the steps and recipes that you followed to reproduce the issue.

**Comment by spiffytech** [comment] 2017-03-28 18:51
Chef isn't updating my task's `frequency` and `frequency_modifier`

```ruby
windows_task 'Alert on long session' do
  command my_script
  frequency :minute  # used to be :hourly
  frequency_modifier 30  # used to be 1
  cwd script_folder
end
```

The Scheduled Task installed on my systems still repeats every 1 hour.

**Comment by NimishaS** [comment] 2017-03-29 06:11
@spiffytech , this issue will be resolved in https://github.com/chef/chef/pull/5886

**Comment by tas50** [comment] 2017-09-09 04:01
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.

**Closed by tas50** 2017-09-09 04:01 UTC
Labels: Type: Bug
