### ISSUE TITLE
Installing multiple features doesn't work with windows_feature_dism install method

### ISSUE THREAD

**Issue by david-in-perth** [chef-cookbooks/windows#479] opened 2017-06-22 14:55 UTC
This issue relates to the feature from pull request #430.

### Cookbook version
3.1.0

### Chef-client version
13.1.31

### Platform Details
Windows 10 (10.0, build 10240)

### Scenario:
Trying to use the `windows_feature` resource to simultaneously install several Windows features to the Windows 10 machine.

### Steps to Reproduce:
Run a `windows_feature` resource that installs multiple features at once, and uses the DISM install method.

E.g.:
```ruby
windows_feature ['NetFx4Extended-ASPNET45', 'WAS-WindowsActivationService'] do
  action :install
  install_method :windows_feature_dism
end
```

### Expected Result:
If available, all features are installed. Otherwise, there is an error listing the features that cannot be installed.

### Actual Result:
Example:
> WARN: Requested feature NetFx4Extended-ASPNET45, WAS-WindowsActivationService is not available on this system.

**Comment by david-in-perth** [comment] 2017-06-22 15:03
The problem appears to be that [line 77][1] doesn't allow for the fact that `new_resource.feature_name` might be an array.
The warning message on line 29 would also need to be updated.

[1]: https://github.com/chef-cookbooks/windows/blob/v3.1.1/resources/feature_dism.rb#L77

**Comment by tas50** [comment] 2018-02-25 05:06
@david-in-perth Thanks for the report. I'm going to try to get this one resolved next week in a major cleanup of the feature code.

**Comment by dpbustos** [comment] 2018-02-28 02:26
I've reproduced this issue too in version 3.5.1. Unable to even install a single feature, given that the string input will be coerced to be an array, and Line 77 still does not support the use of arrays... (Line 69 also looks like it does not support arrays...

I'm currently forcing a depency on version 3.4.4, which does work with single features at a time, given there is no coercing to array for feature_name param.

A related issue is one where features with the source files removed from the OS may not work either due to the Line 77 checking for the not match of regex: "with payload removed". What happens when the source parameter is supplied (targeting the sxs content)? Simplest fix would be to remove checking for "with payload removed"...

**Comment by tas50** [comment] 2018-02-28 02:35
Thanks for the update. I'll see what I can do about the arrays. This is all getting cleaned up in preparation for inclusion into Chef 14 so we want to make sure to resolve all these issues.

**Comment by dpbustos** [comment] 2018-02-28 03:23
No worries and that's great that these cookbooks will be included in Chef 14. If you need further details about what I've found about array support and support features where the sources are not included in the OS, please let me know.

**Comment by tas50** [comment] 2018-03-02 19:02
This is fixed by https://github.com/chef-cookbooks/windows/pull/530

**Closed** 2018-03-02 19:06 UTC
Labels: Type: Bug
